name: ci/gh-actions/cli

on:
  push:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
      - uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
