name: ci/gh-actions/cli

on:
  push:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: packages
        run: |
         apt install ffmpeg -y
      - name: ffmpeg
        run: |
         ffmpeg -i https://debrid.gookie.dev/RlVtbTlHaDRXY24zWDE3emwxdXFjYU5TTkhNVHpidzV1Njc2azIybVU2bw/Blade.Runner.1982.The.Final.Cut.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv -filter:v scale=1366:-1 -c:v hevc -x265-params lossless=1 -c:a copy -c:s copy a.mkv
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
